revert

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -86,20 +86,20 @@ jobs:
       #     ver=$(skopeo inspect docker://${{ env.BASE_IMAGE_URL }}:${{ env.FEDORA_MAJOR_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
       #     echo "VERSION=$ver" >> $GITHUB_OUTPUT
       
-      - name: Get current version
-        id: labels
-        uses: Wandalen/wretry.action@v3.5.0
-        with:
-          attempt_limit: 3
-          attempt_delay: 15000
-          command: |
-            set -eo pipefail
-            ver=$(skopeo inspect docker://${{ env.BASE_IMAGE_URL }}:${{ env.FEDORA_MAJOR_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
-            if [ -z "$ver" ] || [ "null" = "$ver" ]; then
-              echo "inspected image version must not be empty or null"
-              exit 1
-            fi
-            echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV
+      # - name: Get current version
+      #   id: labels
+      #   uses: Wandalen/wretry.action@v3.5.0
+      #   with:
+      #     attempt_limit: 3
+      #     attempt_delay: 15000
+      #     command: |
+      #       set -eo pipefail
+      #       ver=$(skopeo inspect docker://${{ env.BASE_IMAGE_URL }}:${{ env.FEDORA_MAJOR_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
+      #       if [ -z "$ver" ] || [ "null" = "$ver" ]; then
+      #         echo "inspected image version must not be empty or null"
+      #         exit 1
+      #       fi
+      #       echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV
 
       # Build metadata
       - name: Image Metadata
@@ -113,7 +113,7 @@ jobs:
             io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
             org.opencontainers.image.description=${{ env.MY_IMAGE_DESC }}
             org.opencontainers.image.title=${{ env.MY_IMAGE_NAME }}
-            org.opencontainers.image.version=${{ env.SOURCE_IMAGE_VERSION }}
+            org.opencontainers.image.version=${{ env.MY_IMAGE_VERSION }}
 
       # Build image using Buildah action
       - name: Build Image
